# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2017 Luca Weiss <luca@lucaweiss.eu>

# Translations
ts_files = [
  'bg.ts',
  'de.ts',
  'eo.ts',
  'fr.ts',
  'ka.ts',
  'nl.ts',
  'ru.ts',
  'pl.ts',
]
qt.compile_translations(ts_files : ts_files,
                        install : true,
                        install_dir : razergenie_data_dir / 'translations',
                        build_by_default : true)

