# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 Luca Weiss <luca@lucaweiss.eu>

name: macOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - run: brew install qt@6 meson svg2png
      - run: echo "/opt/homebrew/opt/qt@6/bin" >> $GITHUB_PATH
      - run: meson setup builddir
      - run: meson compile -C builddir
